config/routes.rb
VideoShare::Application.routes.draw do
  
  resources :videos do
	  member do
     get 'download'
     get 'play'
	  end
	  
  end
  
  root :to => 'home#index'
  match '/videos/create' => 'videos#create',:as=>'upload'
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,:admin
	def password_required?
   new_record?
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:notice] = "Successfully created User."
			redirect_to users_path
		else
			render :action => 'new'
		end
	end

	def edit
		if current_user.admin?
			@user = User.find(params[:id])
		else
			@user = current_user
		end
	end

	def update
		if current_user.admin?
			@user = User.find(params[:id])
		else
			@user = current_user
		end
		params[:user].delete(:password) if params[:user][:password].blank?
		params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
		if @user.update_attributes(params[:user])
			flash[:notice] = "Successfully updated User."
			redirect_to users_path
		else
			render :action => 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:notice] = "Successfully deleted User."
			redirect_to users_path
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit <%= @user.email.to_s.humanize %></h2>

<%= form_for(@user, :html => { :method => :put,:class=>'data-form'} ) do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p><%= f.label :email %><br />
      <%= f.text_field :email %></p>

    <p><%= f.label :name %><br />
      <%= f.text_field :name %></p>

    <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p>

    <p><%= f.label :admin %><br />
      <%= f.check_box :admin %></p>

    <p><%= f.submit "Update" %></p>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%#= link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<div class="add-asset" style="float:right">
  <%= link_to 'Add User', new_user_path,:class=>"button add" %>
</div>
<div class="listing">
  <table class="listing">
    <thead>
    <tr>
      <th>Email</th>
      <th width="40"></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email%> </td>
        <td><%=link_to image_tag("edit_10.png") ,edit_user_path(user)%>
          <%=link_to image_tag("delete_10.png") ,user,:method=>:delete,:confirm=>"Are You sure you want to delete?" %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h2>Add User</h2>

<%= form_for(@user, :html=>{:class=>'data-form'}) do |f| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.label :email %><br />
    <%= f.text_field :email %></p>

  <p><%= f.label :name %><br />
    <%= f.text_field :name %></p>

  <p><%= f.label :password %><br />
    <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %></p>
    <p><%= f.label :admin %><br />
      <%= f.check_box :admin %></p>
  <p><%= f.submit "Sign up" %></p>
<% end %>