config/routes.rb
VideoShare::Application.routes.draw do
  
  resources :videos do
	  member do
     get 'download'
     get 'play'
	  end
	  
  end
  
  root :to => 'home#index'
  match '/videos/create' => 'videos#create',:as=>'upload'
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_attached_file :asset,
	                 :url => '/:class/:id/:basename.:extension',
                    :path => ':rails_root/attachments/:class/:id/:basename.:extension'
#	validates_attachment_presence :video
  #validates_attachment_content_type :video,
	# :content_type => ['application/x-shockwave-flash', 'application/x-shockwave-flash', 'application/flv', 'video/x-flv','video/quicktime','video/mp4']
	#after_create :move_to_path
  attr_accessor :temp_file_path
	scope :by_name_or_description, lambda{|search_param| where("name Like ? or asset_file_name Like ? or description Like ?","%#{search_param}%","%#{search_param}%","%#{search_param}%") unless search_param.blank?}
 
	def convert_to_mp4
		if self.asset_content_type != "video/mp4"
			Stalker.enqueue('convert_video.to_mp4', :file => self.asset.path)
		end
	end
	
  # handle new param
  def set_nginx_video(video)

   asset = video['asset']
    if asset && asset.respond_to?('[]')
      self.asset = File.new(asset['filepath'])
      self.temp_file_path =asset['filepath']
      self.asset_file_name = asset["original_name"]
      self.asset_content_type = asset["content_type"]
      self.name = video["name"]
      self.description = video["description"]
    end
  end    

  # clean tmp directory used and set new param
  def move_to_path
   if File.exist?(self.asset.path)
    ##MOve to path
    paper_clip_path = "#{Rails.root}/attachments/videos/#{self.id}/"
    FileUtils.mkdir_p(paper_clip_path)
    actual_path = paper_clip_path+self.asset_file_name
    FileUtils.mv(self.temp_file_path,actual_path)
    self.asset = File.new(actual_path)
    self.save!
    #self.convert_to_mp4
   end
 end 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	# GET /videos
	# GET /videos.xml
	load_and_authorize_resource
	def index
		@videos = Video.by_name_or_description(params[:search]).paginate(:page => params[:page], :per_page => 15)
		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @videos }
		end
	end

	def new
		@video = Video.new
		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @video }
		end
	end

	def create

		@video = Video.new
		# FOR NGINX
		puts params
		@video.set_nginx_video(params)
		respond_to do |format|
			if @video.save
				puts @video.temp_file_path
				@video.move_to_path
				format.html { redirect_to(videos_path, :notice => 'Video was successfully created.') }
				format.xml  { render :xml => @video, :status => :created, :location => @video }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /videos/1
	# DELETE /videos/1.xml
	def destroy
		@video = Video.find(params[:id])
		@video.destroy

		respond_to do |format|
			format.html { redirect_to(videos_url) }
			format.xml  { head :ok }
		end
	end

	def show
		@video = Video.find(params[:id])
	end

	def	play
		@video = Video.find(params[:id])
		if @video.asset_content_type !='video/mp4'
			response.headers['X-Accel-Redirect'] = "/attachments/videos/#{@video.id}/#{@video.asset_file_name}.mp4"
		else
			response.headers['X-Accel-Redirect'] = "/attachments/videos/#{@video.id}/#{@video.asset_file_name}"
		end
		response.headers['Content-Type']  = 'video/mp4'
		response.headers['Content-Disposition'] = "inline;filename=#{@video.asset_file_name}"
		render :nothing => true

	end
	def download
		@video = Video.find(params[:id])
		response.headers['X-Accel-Redirect'] = "/attachments"+@video.asset.url.split("?").first
		response.headers['Content-Type']  = @video.asset_content_type
		response.headers['Content-Disposition'] = "attachment;filename=#{@video.asset_file_name}"
		redirect_to video_url(@video)
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<% form_tag(upload_path,:method=>'post', :multipart => true,:class=>'data-form') do  %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
  <label>Name:</label> <br />
   <%= text_field_tag "name" %>
  </div>
 <div class="field">
  <label>Description:</label><br /> <%= text_area_tag "description" %>
  </div>
  <div class="field">
 <%= file_field_tag :asset %>
  </div>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/videos/index.html.erb
<div class="add-asset">
  <div class="grid_12" id="search_form">
    <%= form_tag(videos_path(),:method=>:get) do %>
      <strong> Search : </strong><%= text_field_tag :search %>
      <%= submit_tag "Search"%>
    <% end %>
  </div>

  <div class="grid_4">
    <% if can? :create, Video %>
      <%= link_to 'Add Asset', new_video_path,:class=>"button" %>
    <% end %>
  </div>
  <%= clearing_span %>

  <div class="add-asset" style="float:right"><%= will_paginate @videos %></div>
</div>

<hr class="separator" />
<% @videos.each do |video| %>
  <div class="asset">
    <div class="asset-title"><strong><%= video.name %></strong> : <%= video.asset_file_name %></div>
    <div class="asset-description"><%= video.description %>

    </div>
    <p class="download-link">
      <strong>Download :</strong><%=link_to video.asset_file_name,download_video_path(video) %>
      <% if can? :destroy, Video %>
        <strong>Delete:</strong> <%= link_to image_tag("close_16.png"), video,:method=>:delete,:confirm=>"Are You sure"%>
      <% end %>
    </p>
  </div>
  <hr class="separator" />
<% end %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%=javascript_include_tag "video" %>
<%= stylesheet_link_tag  "video-js"%>

  <script type="text/javascript">
    VideoJS.setupAllWhenReady();
  </script>
  <!-- Begin VideoJS -->
  <div class="video-js-box">
    <!-- Using the Video for Everybody Embed Code http://camendesign.com/code/video_for_everybody -->
    <video id="example_video_1" class="video-js" width="640" height="264" controls="controls" preload="auto">
     <source src="<%= play_video_path(@video) %>" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
     <source src="<%= play_video_path(@video) %>" type='video/ogg; codecs="theora, vorbis"' />
       <!-- Flash Fallback. Use any flash video player here. Make sure to keep the vjs-flash-fallback class. -->
      <object id="flash_fallback_1" class="vjs-flash-fallback" width="640" height="264" type="application/x-shockwave-flash" data="/flash/flowplayer-3.2.7.swf">
        <param name="movie" value="/flash/flowplayer-3.2.7.swf" />
        <param name="allowfullscreen" value="true" />
        <param name="flashvars" value='config={"playlist":[{"url": "<%= play_video_path(@video) %>","autoPlay":false,"autoBuffering":true}]}' />
       </object>
    </video>
 </div>
<p class="vjs-no-video"><strong>Download Video:</strong>
 <%= link_to "Download",download_video_path(@video) %>
</p>