config/routes.rb
VideoShare::Application.routes.draw do
  
  resources :videos do
	  member do
     get 'download'
     get 'play'
	  end
	  
  end
  
  root :to => 'home#index'
  match '/videos/create' => 'videos#create',:as=>'upload'
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'reset','grid','base','application'%>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'application' %>
  <title>Video share <%=raw ((yield(:title) || "Untitled")) %></title>
  <%= yield :head %>
  <%= csrf_meta_tag %>

</head>
<body>
<div class="container_16 every-thing">
  <div class="header">
    <div id="login_header">

      <div id="login_bar_right" class="grid_3 prefix_13">
        <ul>
          <% if !current_user.blank? %>
            <li><%=link_to "Profile  ", edit_user_path(current_user),:class=>'profile',:user_id=>current_user.email %> </li>
            <li><%= link_to "Logout",  logout_path%></li>
          <% else %>
            <li><%#= link_to "Register ", new_user_registration_path %></li>
            <li><%= link_to "Login  ", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="header-row"></div>
    <div id="main_header">
      <div class="header-content">Video Share ..... Railstech</div>
      <div id="main_nav" style="float:right;padding-right:10px;">
        <ul>
          <li class="active_class" id="home"><%= link_to "Home", root_url,:class=>active_class %></li>
          <% if current_user.blank? %>
            <li class="active_class" id="login"><%= link_to "Login", login_path,:class=>active_class %></li>
          <% else %>
            <li class="active_class" id="video"><%= link_to "Videos", videos_path ,:class=>active_class%></li>
            <% if can? :create, User %>
              <li class="active_class" id="users"><%= link_to "Users ", users_path,:class=>active_class %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div id="sub_nav">
    </div>

  </div>
  <%= clearing_span %>
  <div id="content" >
    <div id="main_content" class="<%= main_content_css_class%>">
      <%=raw flash_messages %>
      <%= yield %>

    </div>
    <div id="sidebar" class="<%= sidebar_css_class%>">
      <%=yield :sidebar %>
    </div>
    <%= clearing_span %>
  </div>
  <div class="push"></div>
</div>
<%= clearing_span %>
<div  class="container_16" id="footer-wrapper">
  <div class="footer-row"></div>
  <div id="footer">
    <p class="copyright">&copy; 2010 <a href="http://raistech.com">Amar Daxini</a></p>
  </div>

  <%= yield :javascript %>
  <script>
    function addActive()
    {
      $(".active_class").removeClass('active');
      var active_id = $(".active_class:first a").attr('class');

      $(".active_class").each(function(){
        if($(this).attr('id')==active_id)
        {
          $(this).addClass('active');
          return;
        }


      });
    }
    $(document).ready(function(){

      addActive();
    });
  </script>
</div>
</body>
</html>